### ISSUE TITLE
Poor Accuracy for Webcam to Amazon  OR  DSLR to Amazon

### ISSUE THREAD

**Issue by deep0learning** [sunziping2016/transfer-tensorflow#3]
I found poor accuracy for W --> A  and D --> A using DAN model.  I got just only 50.3 % accuracy. Is it a bug? But, for other transfer task, the results are alright.

**Comment by sunziping2016** [comment]
[Here](https://arxiv.org/pdf/1502.02791.pdf) is the original paper.

There are only 498 images in DSLR and  795 images in Webcam. It would be surprising if someone can do much better training these small dataset.

**Comment by deep0learning** [comment]
Thank you so much for your answer. Yes I understood now.
